language: node_js
sudo: false
node_js:
- lts/*
before_script:
- npm run build
after_success:
- npx nyc report --reporter=text-lcov | npx coveralls
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: Wnx6gm2kkoRXj/pYMxt++nw3JA8vFbw38THSc4MqQtwaivdrDAOTXE18BaFtkzSbn+nRkq7aT/x/GdUgsRVMvVvHxruZ4/GJKxe2yIx2dycN9QObFzksuvrRwJvl2Yv2LiIMtgxFFaSHoZmo8/P5ELGLMSj7k9Y3So8dR6boF/Y=
  on:
    tags: true
    repo: noflo/noflo
  skip_cleanup: true
addons:
  chrome: stable
